/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HangMan;
import java.io.*;
import javax.swing.*;
import java.util.*;
/**
 *
 * @author Admin
 */
public class GUI_Andrew extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Andrew
     */
    public GUI_Andrew() {               
        initComponents();
          switch (randomWords.length()) {       
               case 3:
                   char4.setVisible(false);
                   char5.setVisible(false);
                   char6.setVisible(false);
                   char7.setVisible(false);
                   char8.setVisible(false);
                   char9.setVisible(false);
                   break;
               case 4:
                   char5.setVisible(false);
                   char6.setVisible(false);
                   char7.setVisible(false);
                   char8.setVisible(false);
                   char9.setVisible(false);
                   break;
               case 5:
                   char6.setVisible(false);
                   char7.setVisible(false);
                   char8.setVisible(false);
                   char9.setVisible(false);
                   break;
               case 6:
                   char7.setVisible(false);
                   char8.setVisible(false);
                   char9.setVisible(false);
                   break;
               case 7:
                   char8.setVisible(false);
                   char9.setVisible(false);
                   break;
               case 8:
                   char9.setVisible(false);
                   break;
               default:
                   break;
           }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    String [] secretWords = {"owl","java","panic","forbid","jocular","integral","hostility"};
    //String [] secretWords = readString("Andrew.txt");
    
    public int random = (int)(Math.random()*6);
    public int wrongCounts ;
    public int correctCounts;
    public String randomWords = secretWords[random];
    
    
    private ImageIcon han1 = new ImageIcon(getClass().getResource("error1.png"));
    private ImageIcon han2 = new ImageIcon(getClass().getResource("error2.png"));
    private ImageIcon han3 = new ImageIcon(getClass().getResource("error3.png"));
    private ImageIcon han4 = new ImageIcon(getClass().getResource("error4.png"));
    private ImageIcon han5 = new ImageIcon(getClass().getResource("error5.png"));
    private ImageIcon han6 = new ImageIcon(getClass().getResource("error6.png"));
    private ImageIcon han7 = new ImageIcon(getClass().getResource("error7.png"));
    private ImageIcon manAlive = new ImageIcon(getClass().getResource("wonphoto.gif"));
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        char1 = new javax.swing.JLabel();
        char2 = new javax.swing.JLabel();
        char3 = new javax.swing.JLabel();
        char4 = new javax.swing.JLabel();
        char5 = new javax.swing.JLabel();
        char6 = new javax.swing.JLabel();
        char7 = new javax.swing.JLabel();
        char8 = new javax.swing.JLabel();
        char9 = new javax.swing.JLabel();
        incorrectGuess = new javax.swing.JLabel();
        count = new javax.swing.JLabel();
        balanceTries = new javax.swing.JLabel();
        tries = new javax.swing.JLabel();
        welcomeUser = new javax.swing.JLabel();
        tryLetter = new javax.swing.JButton();
        hint = new javax.swing.JLabel();
        clueForPlayer = new javax.swing.JLabel();
        userInput = new javax.swing.JTextField();
        picture = new javax.swing.JButton();
        hintAnswer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HANGMAN GAME");

        char1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        char1.setText(" X");

        char2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        char2.setText(" X");

        char3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        char3.setText(" X");

        char4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        char4.setText(" X");

        char5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        char5.setText(" X");

        char6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        char6.setText(" X");

        char7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        char7.setText(" X");

        char8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        char8.setText(" X");

        char9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        char9.setText(" X");

        incorrectGuess.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        incorrectGuess.setText("INCORRECT GUESS :");

        count.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        balanceTries.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        balanceTries.setText("BALANCE TRIES     :");

        tries.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        welcomeUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        welcomeUser.setText("   WELCOME TO HANGMAN GAME !!!");

        tryLetter.setBackground(new java.awt.Color(0, 0, 255));
        tryLetter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tryLetter.setText("TRY !!!");
        tryLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryLetterActionPerformed(evt);
            }
        });

        hint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hint.setText("HELP :");

        clueForPlayer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangMan/error0.png"))); // NOI18N
        picture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pictureActionPerformed(evt);
            }
        });

        hintAnswer.setBackground(new java.awt.Color(255, 51, 51));
        hintAnswer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hintAnswer.setText("HINT!!!");
        hintAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintAnswerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hint, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clueForPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(incorrectGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(char1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(char2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(char3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(char4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hintAnswer))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(welcomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tryLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(char5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(char6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(char7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(char9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(char8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(balanceTries, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tries, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(char1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(char2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(char3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(char4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(char5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(char6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(char7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(char9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(char8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(incorrectGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(balanceTries, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tries, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hintAnswer)
                            .addComponent(tryLetter))
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(welcomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(picture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clueForPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hint, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tryLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryLetterActionPerformed
        // TODO add your handling code here:
       try{ 
        char[] userAnswer = new char[9];
       
        
        for(int i=0;i<randomWords.length();i++){
            userAnswer[i] =randomWords.charAt(i);
            
            
        }
         
            String userEnter = userInput.getText().toLowerCase();
            char answer = userEnter.charAt(0);
            int  counts = 0;
            
            for(int i=0;i<randomWords.length();i++){
                  if(answer == userAnswer[i]){
                      switch(i){
                          case 0:
                        char1.setText(""+answer);
                            break;
                          case 1:
                        char2.setText(""+answer);
                            break;
                          case 2:
                        char3.setText(""+answer);
                            break;
                          case 3:
                        char4.setText(""+answer);
                            break;
                          case 4:
                        char5.setText(""+answer);
                            break; 
                          case 5:
                        char6.setText(""+answer);
                            break;
                          case 6:
                        char7.setText(""+answer);
                            break;
                          case 7:
                        char8.setText(""+answer);
                            break;
                          case 8:
                        char9.setText(""+answer);
                            break; 
                          default:
                              break;
                      }
                      correctCounts++;
                  }else{
                        counts++;
                    }
               
                if(counts == randomWords.length()){
                    counts =0;
                    wrongCounts++;
                    count.setText(""+wrongCounts);
                    tries.setText(""+(7-wrongCounts));
                }
                userInput.setText(null);
                if(correctCounts == randomWords.length()){
                     picture.setIcon(manAlive);
                    JOptionPane.showMessageDialog(rootPane,"TRIUMPH!!! WELDONE","RESULT OF T"
                             + "HE GAME",JOptionPane.INFORMATION_MESSAGE);
                   System.exit(0);
                }
                }
        }catch(Exception e){
                 JOptionPane.showMessageDialog(rootPane,"ENTER A SINGEL CHARECTER","RESULT OF T"
                             + "HE GAME",JOptionPane.INFORMATION_MESSAGE);
        }

        switch(wrongCounts){
            case 1:
                picture.setIcon(han1);
                break;
            case 2:
                picture.setIcon(han2);
                break;
            case 3:
                picture.setIcon(han3);
                break;
            case 4:
                picture.setIcon(han4);
                break;
            case 5:
                picture.setIcon(han5);
                break;
            case 6:
                picture.setIcon(han6);
                break;
            case 7:
                picture.setIcon(han7);
                JOptionPane.showMessageDialog(rootPane,"SORRY BETTER LUCK NEXT TIME!!!!!","RESULT OF T"
                             + "HE GAME",JOptionPane.INFORMATION_MESSAGE);
                 System.exit(0);
                break;
            default:
                break;
        }
        
    }//GEN-LAST:event_tryLetterActionPerformed
   
    private void pictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pictureActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pictureActionPerformed

    private void hintAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintAnswerActionPerformed
        // TODO add your handling code here:
           switch (randomWords){
               case "owl":                    
                   clueForPlayer.setText("Which don't sleep at nigth");
                   break;
               case "java": 
                   clueForPlayer.setText("One of the coding language"); 
                   break;
               case "panic":
                   clueForPlayer.setText("sudden uncontrollable fear or anxiety");
                   break;
               case "forbid":
                   clueForPlayer.setText("refuse to allow");
                   break;
               case "jocular":
                   clueForPlayer.setText("fond of or characterized by joking");
                   break;
                case "integral":
                   clueForPlayer.setText("necessary to make a whole complete");
                   break;
               case "hostility":
                   clueForPlayer.setText("unfriendliness or opposition");
                   break;
               default :
                   break;
                   }
           
    }//GEN-LAST:event_hintAnswerActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Andrew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Andrew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Andrew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Andrew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Andrew().setVisible(true);
            }
        });
    }
    public static String[] readString(String file){
        int noOfLine = 0;
        try{
            Scanner sc = new Scanner(new File("Andrew.txt"));
            while(sc.hasNextLine()){
                noOfLine++;
            }
            String[] textWords =new String[noOfLine];
            Scanner sc1 = new Scanner(new File("Andrew.txt"));
            for(int i=0; i<noOfLine; i++){
                textWords[i] = sc1.nextLine();
                System.out.println(textWords[i]);
            }
            return textWords;
             
        }catch(FileNotFoundException e){
            System.err.println(e);
        }
            return null;
           
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balanceTries;
    private javax.swing.JLabel char1;
    private javax.swing.JLabel char2;
    private javax.swing.JLabel char3;
    private javax.swing.JLabel char4;
    private javax.swing.JLabel char5;
    private javax.swing.JLabel char6;
    private javax.swing.JLabel char7;
    private javax.swing.JLabel char8;
    private javax.swing.JLabel char9;
    private javax.swing.JLabel clueForPlayer;
    private javax.swing.JLabel count;
    private javax.swing.JLabel hint;
    private javax.swing.JButton hintAnswer;
    private javax.swing.JLabel incorrectGuess;
    private javax.swing.JButton picture;
    private javax.swing.JLabel tries;
    private javax.swing.JButton tryLetter;
    private javax.swing.JTextField userInput;
    private javax.swing.JLabel welcomeUser;
    // End of variables declaration//GEN-END:variables
}
